name: Deno

on:
  push:
    branches: ["master", "ci-test"]
  pull_request:
    branches: ["master", "ci-test"]

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Setup repo
        uses: actions/checkout@v3
        with:
          submodules: recursive
      
      - name: Setup Node.js environment
        uses: actions/setup-node@v2.5.2
        with:
          node-version: 18.x
      
      - name: Install SnarkJS
        run: |
          npm install -g snarkjs
      
      - name: Installing Circom
        uses: baptiste0928/cargo-install@feat/git-install
        with:
          crate: circom
          git: https://github.com/iden3/circom
          tag: v2.1.5
      
      - name: Build with Make
        run: make build

      - name: Setup Deno
        # uses: denoland/setup-deno@v1
        uses: denoland/setup-deno@9db7f66e8e16b5699a514448ce994936c63f0d54
        with:
          deno-version: v1.x

      - name: Verify formatting
        run: deno fmt --check

      - name: Run linter
        run: deno lint
