name: Deno

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Setup repo
        uses: actions/checkout@v3
        with:
          submodules: recursive
      
      - name: Setup Node.js environment
        uses: actions/setup-node@v2.5.2
        with:
          node-version: 18.x
      
      - name: Install SnarkJS
        run: |
          npm install -g snarkjs
      
      - name: Install Circom
        id: download_release_asset
        uses: i3h/download-release-asset@v1
        with:
          owner: iden3
          repo: circom
          tag: v2.1.5
          file: circom-linux-amd64
          path: deps/circom
      
      - name: Add Execute Permissions
        run: chmod +x deps/circom

      - name: Build with Make
        run: make build
        env:
          CIRCOM: deps/circom

      - name: Setup Deno
        # uses: denoland/setup-deno@v1
        uses: denoland/setup-deno@9db7f66e8e16b5699a514448ce994936c63f0d54
        with:
          deno-version: v1.x

      - name: Verify formatting
        run: deno fmt --check

      - name: Run linter
        run: deno lint

      - name: Run tests
        run: deno test -A
