name: Deno

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Setup repo
        uses: actions/checkout@v3

      - name: Setup Rust
        uses: ATiltedTree/setup-rust@v1.0.5
        with:
          rust-version: stable
      
      - name: Setup Node.js environment
        uses: actions/setup-node@v2.5.2
        with:
          node-version: 18.x
      
      - name: Install Dependencies
        run: bash ./install_deps.sh
      
      - name: Build with Make
        run: make build

      - name: Setup Deno
        # uses: denoland/setup-deno@v1
        uses: denoland/setup-deno@9db7f66e8e16b5699a514448ce994936c63f0d54
        with:
          deno-version: v1.x

      - name: Verify formatting
        run: deno fmt --check

      - name: Run linter
        run: deno lint

      - name: Run tests
        run: deno test -A
